### ISSUE TITLE
Preview button shows but doesn't do anything

### ISSUE THREAD

**Issue by schnaader** [revathskumar/gist-markdown-preview#2]
- Windows 7 64-Bit
- Chrome 63.0.3239.108 64-Bit
- [Public gist](https://gist.github.com/schnaader/96ba18f4246910dd8ae0f0df093634d5) I created to test it 

A preview button is created and I can click it, but nothing changes and still looks as in the screenshot below:

![image](https://user-images.githubusercontent.com/7848769/34460579-f4256bb8-ee12-11e7-80da-dfe97cb53a3e.png)

**Comment by revathskumar** [comment]
@schnaader Thanks for reporting. This was due to class name change by github. Did a fix and merged to master. will do a release soon.
