### ISSUE TITLE
Looks like it doesn't work now

### ISSUE THREAD

**Issue by jerrygreen** [revathskumar/gist-markdown-preview#9]
Chrome Version 80.0.3987.132 (Official Build) (64-bit)

**Comment by revathskumar** [comment]
Seems like it is still working fine. 
Tested on Chrome 80 (Linux). 

 if its still not working for you, can you share more details?

**Comment by ismailyenigul** [comment]
Does not work on Macos 76.0.1 (64-bit) too
![gist-screenshot](https://user-images.githubusercontent.com/2566232/81497383-d3a1d600-92c6-11ea-96db-28ba2681f045.png)

**Comment by revathskumar** [comment]
@ismailyenigul Try the filename ends with `.md`. Eg: `test.md`.

**Comment by ismailyenigul** [comment]
Thanks @revathskumar 
 I was trying with .yml extension. It works fine with .md
